Add a docs/ commit detection

diff --git a/.github/workflows/pull_requests.yaml b/.github/workflows/pull_requests.yaml
--- a/.github/workflows/pull_requests.yaml
+++ b/.github/workflows/pull_requests.yaml
@@ -4,8 +4,22 @@ on:
     pull_request:
         paths:
             - src/generator/*
+            - .github/workflows/pull_requests.yaml
 
 jobs:
+    no-publish:
+        name: No publication on generator sources
+        runs-on: ubuntu-latest
+        steps:
+            - name: Get the code
+              uses: actions/checkout@v3
+            - name: Make sure no publication was committed
+              run: |
+                publish_count=$(ls . | grep "docs" | wc -l)
+                if [ 0 -lt $publish_count ]; then
+                  echo "Published content detected. Failing the job."
+                  exit 1
+                fi
     lint:
         name: Lint the generator
         runs-on: ubuntu-latest
@@ -21,7 +35,7 @@ jobs:
               cd src
               python3 -m pip install -r requirements.txt
           - name: Lint the code
-            run: pylint generator
+            run: pylint src/generator
 
     format:
         name: Check the generator format
@@ -38,4 +52,4 @@ jobs:
               cd src
               python3 -m pip install -r requirements.txt
           - name: Check the format
-            run: black --check --no-color --diff generator
+            run: black --check --no-color --diff src/generator
